FROM openjdk:14-jdk-alpine
MAINTAINER bmc
ADD ./target/appointmentService.jar /opt/app/appointmentService.jar
WORKDIR /opt/app
ENV PATH="${PATH}:${JAVA_HOME}/bin"
EXPOSE 8087
ENTRYPOINT [ "java", "-jar", "/opt/app/appointmentService.jar"]