FROM openjdk:14-jdk-alpine
MAINTAINER bmc
ADD ./target/doctorService.jar /opt/app/doctorService.jar
WORKDIR /opt/app
ENV PATH="${PATH}:${JAVA_HOME}/bin"
EXPOSE 8081
ENTRYPOINT [ "java", "-jar", "/opt/app/doctorService.jar"]