FROM openjdk:14-jdk-alpine
MAINTAINER bmc
ADD ./target/authService.jar /opt/app/authService.jar
WORKDIR /opt/app
ENV PATH="${PATH}:${JAVA_HOME}/bin"
EXPOSE 9090
ENTRYPOINT [ "java", "-jar", "/opt/app/authService.jar"]