FROM openjdk:14-jdk-alpine
MAINTAINER bmc
ADD ./target/apiGateway.jar /opt/app/apiGateway.jar
WORKDIR /opt/app
ENV PATH="${PATH}:${JAVA_HOME}/bin"
EXPOSE 8080
ENTRYPOINT [ "java", "-jar", "/opt/app/apiGateway.jar"]