FROM openjdk:14-jdk-alpine
MAINTAINER bmc
ADD ./target/ratingService.jar /opt/app/ratingService.jar
WORKDIR /opt/app
ENV PATH="${PATH}:${JAVA_HOME}/bin"
EXPOSE 8090
ENTRYPOINT [ "java", "-jar", "/opt/app/ratingService.jar"]