FROM openjdk:14-jdk-alpine
MAINTAINER bmc
ADD ./target/notificationService.jar /opt/app/notificationService.jar
WORKDIR /opt/app
ENV PATH="${PATH}:${JAVA_HOME}/bin"
EXPOSE 8095
ENTRYPOINT [ "java", "-jar", "/opt/app/notificationService.jar"]