package com.bmc.ratingservice.security;

public enum ApplicationPermission {
    PAYMENT,
    DOCTOR_AVAILABILITY_UPDATE,
    DOCTOR_AVAILABILITY,
    BOOK_APPOINTMENT,
    APPOINTMENT_DETAILS,
    USER_APPOINTMENTS,
    SEND_PRESCRIPTION,
    DOCTOR_INFO,
    UPLOAD_DOCTOR_DOCUMENTS,
    APPROVE_REGISTRATION,
    REJECT_REGISTRATION,
    TOP_20_DOCTOR_INFO,
    DOCTOR_INFO_ON_ID,
    POST_USER_INFO,
    GET_USER_INFO;
}
