FROM openjdk:14-jdk-alpine
MAINTAINER bmc
ADD ./target/userService.jar /opt/app/userService.jar
WORKDIR /opt/app
ENV PATH="${PATH}:${JAVA_HOME}/bin"
EXPOSE 8083
ENTRYPOINT [ "java", "-jar", "/opt/app/userService.jar"]